### ISSUE TITLE
Manifest Error

### ISSUE THREAD

**Issue by Turtle011** [i0Z3R0/Boxel-Rebound-Hack#3]
The error is:
~\Downloads\Boxel-Rebound-Hack-main\Boxel-Rebound-Hack-main\Boxel Rebound Hack
Error
Manifest file is missing or unreadable
Could not load manifest

**Comment by Mclaren-720S** [comment]
Same, Please help someone

**Comment by i0Z3R0** [comment]
The extension still works for me. You have to select the folder named "Boxel Rebound" after extracting the zip. The folder "Boxel Rebound" should contain a folder named www and the manifest.json file. Make sure you select the Boxel Rebound folder, not www. 
Let me know if this fixes the issue for you. 
@Turtle011 @Mclaren-720S

**Comment by Turtle011** [comment]
Yep works!

**Comment by Turtle011** [comment]
closing :) thanks!
