### ISSUE TITLE
Unable to download file

### ISSUE THREAD

**Issue by ghost** [i0Z3R0/Boxel-Rebound-Hack#4]
Error: 
This site can’t provide a secure connectionraw.githubusercontent.com sent an invalid response.
[Try running Windows Network Diagnostics](javascript:diagnoseErrors()).
ERR_SSL_PROTOCOL_ERROR

This occurs whenever I try to download the file

**Comment by i0Z3R0** [comment]
@mrturrtle Seems like it's an issue with your network or something… maybe try running windows network diagnostics. 
Here's a link to the program on Google Drive: [https://drive.google.com/file/d/1r3VWW52igC8lRCsCgHocL2NF_kbuhruz/view?usp=sharing](https://drive.google.com/file/d/1r3VWW52igC8lRCsCgHocL2NF_kbuhruz/view?usp=sharing)
